name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Navigate to repo
      run: cd $GITHUB_WORKSPACE
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
    - name: Install Wrangler
      run: npm i @cloudflare/wrangler@1.8.3 -g
    - name: Install Workers script deps
      run: npm install
    - name: Publish Worker
      run: wrangler publish -e production
      env:
        CF_API_TOKEN: ${{ secrets.CF_WORKERS_TOKEN }}